#服务名
spring:
  application:
    name: xiaoyu-feign-system
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8850/nacos

#springboot监控暴漏端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.xiaoyu.feign.service.DeptFeignService: debug