#服务名
spring:
  application:
    name: xiaoyu-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8850/nacos #Nacos服务注册中心(集群)地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置 Sentinel dashboard 地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    gateway:
      # 开启动态路由，默认值为 true，即默认开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
      #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
      - id: xiaoyu-feign
        uri: lb://xiaoyu-feign #动态路由，使用服务名代替上面的具体带端口
        predicates:
        #以下是断言条件，必选全部符合条件
        #  - Path=/dept/list/**               #断言，路径匹配 注意：Path 中 P 为大写
        - Method=GET #只能时 GET 请求时，才能访问
        - Path=/**
#        filters:
#        - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id 值为 1024
#        - PrefixPath=/dept #在请求路径前面加上 /dept


#springboot监控暴漏端口
management:
  endpoints:
    web:
      exposure:
        include: "*"