
#服务名
spring:
  application:
    name: xiaoyu-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8850/nacos

#以下配置信息并不是默认配置，而是我们自定义的配置，目的是不在 Controller 内硬编码服务提供者的服务名
service-url:
  nacos-user-service: http://xiaoyu-provider