spring:
  application:
    name: xiaoyu-oss
  redis:
    #    cluster:  集群配置
    #      nodes:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    connect-timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms



management:
  endpoints:
    web:
      exposure:
        include: "*"