
#端口号
server:
  port: 8401
#服务名
spring:
  application:
    name: xiaoyu-sentienl
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8850/nacos #Nacos服务注册中心(集群)地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置 Sentinel dashboard 地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口


#springboot监控暴漏端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
